name: Streamlit App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install additional testing dependencies
        pip install pytest
        
    - name: Verify imports
      run: |
        python -c "
        # Test if all imports work
        try:
            import streamlit
            import pandas as pd
            import matplotlib.pyplot as plt
            import seaborn as sns
            print('✅ All imports successful!')
            print(f'Streamlit version: {streamlit.__version__}')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "
    
    - name: Check Python syntax
      run: |
        python -m py_compile user_engagement_dashboard.py
        echo "✅ Python syntax is valid"
    
    - name: Basic functionality test
      run: |
        # Test that the file can be imported without running Streamlit
        python -c "
        import ast
        with open('user_engagement_dashboard.py', 'r') as file:
            code = file.read()
        
        # Parse the code to check syntax
        ast.parse(code)
        print('✅ Dashboard code syntax is valid')
        
        # Check if it's a Streamlit app (look for streamlit commands)
        if 'streamlit' in code.lower():
            print('✅ Streamlit app detected')
        "
